'use client';
import {useState,useEffect,useMemo,useRef} from 'react';
import {Radar,ArrowUpRight,RefreshCw,Search,Wallet,Star,Activity,ChevronRight,AlertTriangle} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {PriceChart} from '@/components/price-chart';
import {type Pool,type Candle,type Features,chains,validAddress,isTargetPair,pairLabel,volumeLabel,evaluate,features,money} from '@/lib/engine';
import {AUTO_REFRESH_MS,startAutoRefresh} from '@/lib/auto-refresh';
import {useTrackerTools} from '@/hooks/use-tracker-tools';
import allStudies from '@/lib/studies.json';
const studies=allStudies.filter(s=>isTargetPair({chain:s.chain,symbol:s.baseSymbol,quote:s.quote}));
import {poolAppLink} from '@/lib/krystal';
type PoolResponse={pools:Pool[];errors?:{chain:string;message:string}[];coverage?:string;error?:string};
type HistoryResponse={candles:Candle[];error?:string};
type SortKey='score'|'pool5m'|'token1h';
const sortLabels:Record<SortKey,string>={score:'Оценка',pool5m:'Объём пула · 5 минут',token1h:'Объём токена · 1 час'};
type Mode='live'|'favorites'|'history';
const labels:Record<string,string>={solana:'Solana',robinhood:'Robinhood',bsc:'BSC',base:'Base',all:'Все сети'};
const pct=(v:number|null|undefined)=>v==null?'н/д':(v>0?'+':'')+v.toFixed(1)+'%';
const short=(s:string)=>s.slice(0,7)+'…'+s.slice(-5);
export default function Home(){
 const [mode,setMode]=useState<Mode>('live'),[chain,setChain]=useState('solana'),[feed,setFeed]=useState('trending');
 const [sortBy,setSortBy]=useState<SortKey>('score'),[sortDirection,setSortDirection]=useState<'desc'|'asc'>('desc');
 const [capital,setCapital]=useState('200'),[horizon,setHorizon]=useState('1'),[minTvl,setMinTvl]=useState('10000');
 const [query,setQuery]=useState(''),[lookup,setLookup]=useState(''),[auto,setAuto]=useState(true);
 const [pools,setPools]=useState<Pool[]>([]),[favorites,setFavorites]=useState<Pool[]>([]),[loaded,setLoaded]=useState(false);
 const [selectedId,setSelectedId]=useState(''),[studyId,setStudyId]=useState('001.json');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[coverage,setCoverage]=useState('');
 const busyRef=useRef(busy);busyRef.current=busy;
 const [localSource,setLocalSource]=useState(false),[connecting,setConnecting]=useState(false);
 const apiBase=localSource?'http://127.0.0.1:18767':'';
 async function connectLocal(){setConnecting(true);try{const r=await fetch('http://127.0.0.1:18767/health',{signal:AbortSignal.timeout(10000)});const d=await r.json() as {service?:string};if(!r.ok||d.service!=='PULL-local')throw new Error();localStorage.setItem('pull-local-source','1');setLocalSource(true);setRefresh(v=>v+1);}catch{setError('Не удалось подключить компьютер. Запустите notifier/start-collector.ps1 и разрешите сайту доступ к локальной сети в браузере.');}finally{setConnecting(false);}}
 const [lastChecked,setLastChecked]=useState<number|null>(null);
 const [refresh,setRefresh]=useState(0),[now,setNow]=useState(()=>Date.now());
 const [candles,setCandles]=useState<Candle[]>([]),[chartBusy,setChartBusy]=useState(false),[chartError,setChartError]=useState('');
 const [fee,setFee]=useState(''),[share,setShare]=useState(''),[cost,setCost]=useState('1');
 const favRef=useRef(favorites);useEffect(()=>{favRef.current=favorites;},[favorites]);const favKey=favorites.map(p=>p.id).sort().join('|');
 const amount=Math.max(1,Math.min(1000000,Number(capital)||200));
 useEffect(()=>{try{setLocalSource(localStorage.getItem('pull-local-source')==='1');const saved=JSON.parse(localStorage.getItem('pull-favorites-v1')||'[]');if(Array.isArray(saved))setFavorites(saved.filter(p=>p&&chains.includes(p.chain)&&validAddress(p.address)&&validAddress(p.token)&&typeof p.id==='string'&&typeof p.symbol==='string'&&typeof p.fetchedAt==='number').slice(0,30));const st=JSON.parse(localStorage.getItem('pull-settings-v1')||'{}');if(['score','pool5m','token1h'].includes(st.sortBy))setSortBy(st.sortBy);if(['asc','desc'].includes(st.sortDirection))setSortDirection(st.sortDirection);if(Number(st.capital)>0)setCapital(String(st.capital));if(['0.25','1','4'].includes(st.horizon))setHorizon(st.horizon);}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('pull-favorites-v1',JSON.stringify(favorites));localStorage.setItem('pull-settings-v1',JSON.stringify({capital:amount,horizon,sortBy,sortDirection}));}catch{}},[favorites,amount,horizon,sortBy,sortDirection,loaded]);
 useEffect(()=>{if(!auto||mode==='history')return;return startAutoRefresh(document,window,()=>{setRefresh(v=>v+1);setNow(Date.now());},()=>busyRef.current);},[auto,mode]);
 useEffect(()=>{
  if(!loaded||mode==='history')return;
  const ctrl=new AbortController();const timeout=setTimeout(()=>ctrl.abort(),25000);let cancelled=false;setBusy(true);setError('');
  const snapshotKey='pull-snapshot:'+JSON.stringify([apiBase,mode,chain,feed,lookup,favKey]);
  let previous:Pool[]=[];try{const saved=JSON.parse(sessionStorage.getItem(snapshotKey)||'[]');if(Array.isArray(saved))previous=saved.filter(p=>p&&typeof p.fetchedAt==='number'&&Date.now()-p.fetchedAt<86400000);}catch{}
  setPools(previous);
  async function run(){try{
   let result:{pools:Pool[];errors?:{chain:string;message:string}[];coverage?:string};
   if(mode==='favorites'){
    const saved=favRef.current.filter(p=>chain==='all'||p.chain===chain);
    if(!saved.length){setPools([]);setCoverage('Добавьте пул звёздочкой в радаре');return;}
    const groups=chains.flatMap(c=>{const ids=saved.filter(p=>p.chain===c).map(p=>p.address);return Array.from({length:Math.ceil(ids.length/10)},(_,i)=>({chain:c,ids:ids.slice(i*10,i*10+10)}));});
    const responses=await Promise.all(groups.map(async g=>{const r=await fetch(apiBase+'/api/pools?chain='+g.chain+'&ids='+g.ids.slice(0,10).join(','),{signal:ctrl.signal});return r.json() as Promise<PoolResponse>;}));
    result={pools:responses.flatMap(r=>r.pools||[]),errors:responses.flatMap(r=>r.errors||[]),coverage:'Избранные пулы · хранится в этом браузере'};
    const received=new Set(result.pools.map(p=>p.id.toLowerCase()));const absent=saved.filter(p=>!received.has(p.id.toLowerCase()));
    result.pools.push(...absent.map(p=>({...p,fetchedAt:0})));if(absent.length)result.errors?.push({chain:'',message:'Часть пулов не обновилась; их оценки отключены.'});
   }else{
    const r=await fetch(apiBase+'/api/pools?chain='+chain+'&feed='+feed+(lookup?'&token='+encodeURIComponent(lookup):''),{signal:ctrl.signal});const data=await r.json() as PoolResponse;
    if(!r.ok&&!data.pools?.length)throw new Error(data.error||data.errors?.map((e:{message:string})=>e.message).join(' ')||'Источник недоступен');result=data;
   }
   if(cancelled)return;
   if(result.errors?.length){const failed=new Set(result.errors.map(e=>e.chain));const ids=new Set(result.pools.map(p=>p.id));result.pools.push(...previous.filter(p=>failed.has(p.chain)&&!ids.has(p.id)));}
   try{sessionStorage.setItem(snapshotKey,JSON.stringify(result.pools));}catch{}
   setLastChecked(Date.now());setPools(result.pools);setCoverage(result.coverage||'');setError((result.errors||[]).map(e=>(e.chain?(labels[e.chain]||e.chain)+': ':'')+e.message).join(' '));
   setSelectedId(id=>result.pools.some(p=>p.id===id)?id:result.pools[0]?.id||'');setNow(Date.now());
  }catch(e){if(!cancelled){setError((localSource?'Локальный сборщик недоступен. Проверьте, что он запущен и доступ к локальной сети разрешён.':e instanceof Error?e.message:'Ошибка запроса')+(previous.length?' Показаны сохранённые данные.':''));setPools(previous);setNow(Date.now());}}finally{clearTimeout(timeout);if(!cancelled)setBusy(false);}}
  void run();return()=>{cancelled=true;clearTimeout(timeout);ctrl.abort();};
 },[apiBase,mode,chain,feed,lookup,refresh,loaded,favKey]);
 const ranked=useMemo(()=>pools.filter(isTargetPair).map(p=>({pool:p,rating:evaluate(p,amount,Number(horizon),now)})).filter(({pool:p})=>(p.liquidity===null||p.liquidity>=Math.max(0,Number(minTvl)||0))&&(!query||validAddress(query.trim())||p.symbol.toLowerCase().includes(query.toLowerCase())||p.quote.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>{const av=sortBy==='pool5m'?a.pool.v5:sortBy==='token1h'?a.pool.tokenV1:a.rating.score;const bv=sortBy==='pool5m'?b.pool.v5:sortBy==='token1h'?b.pool.tokenV1:b.rating.score;const aMissing=av==null||!Number.isFinite(av),bMissing=bv==null||!Number.isFinite(bv);if(aMissing!==bMissing)return aMissing?1:-1;return (!aMissing&&!bMissing?(sortDirection==='desc'?bv!-av!:av!-bv!):0)||a.pool.id.localeCompare(b.pool.id);}),[pools,amount,horizon,minTvl,query,now,sortBy,sortDirection]);
 useTrackerTools({mode,pools:ranked.map(({pool:p,rating:r})=>({id:p.id,symbol:p.symbol,chain:p.chain,score:r.score,regime:r.regime}))},(c,h)=>{setCapital(String(c));setHorizon(String(h));});
 const selected=ranked.find(p=>p.pool.id===selectedId)||ranked[0],activePool=mode==='history'?null:selected?.pool;
 useEffect(()=>{if(!activePool)return;const ctrl=new AbortController();const id=activePool.id;fetch(apiBase+'/api/pool-fee?'+new URLSearchParams({chain:activePool.chain,token:activePool.token,pool:activePool.address}),{signal:ctrl.signal}).then(r=>r.json() as Promise<{feePercent:number|null;feeSource?:string}>).then(data=>{if(!ctrl.signal.aborted&&data.feePercent!=null)setPools(list=>list.map(p=>p.id===id?{...p,feePercent:data.feePercent,feeSource:data.feeSource}:p));}).catch(()=>{});return()=>ctrl.abort();},[apiBase,activePool?.id,activePool?.fetchedAt]);
 const historical=studies.filter(s=>(chain==='all'||s.chain===chain)&&(!query||s.symbol.toLowerCase().includes(query.toLowerCase())));
 const study=historical.find(s=>s.id===studyId)||historical[0]||studies[0];
 const lpLink=mode==='history'?poolAppLink(study.chain,study.pool):activePool?poolAppLink(activePool.chain,activePool.address,activePool.lpDex||activePool.dex):null;
 const [requestedChart,setRequestedChart]=useState('');
 const chartIdentity=activePool?activePool.id+':'+activePool.token:'';
 const chartUrl=mode==='history'?'/research/'+study.id:activePool&&requestedChart===chartIdentity?apiBase+'/api/history?'+new URLSearchParams({chain:activePool.chain,pool:activePool.address,token:activePool.token}):null;
 const [chartRetry,setChartRetry]=useState(0);
 const requestCandles=()=>{setRequestedChart(chartIdentity);setChartRetry(v=>v+1);};
 useEffect(()=>{
  setCandles([]);setChartError('');setChartBusy(true);const ctrl=new AbortController();
  const url=chartUrl;
  if(!url){setChartBusy(false);return;}
  fetch(url,{signal:AbortSignal.any([ctrl.signal,AbortSignal.timeout(25000)])}).then(async r=>{const data=await r.json() as HistoryResponse|Candle[];if(!r.ok)throw new Error(('error' in data&&data.error)||'Нет графика');return data;}).then(data=>{if(ctrl.signal.aborted)return;const raw:Candle[]=Array.isArray(data)?data:data.candles;setCandles([...new Map(raw.map(c=>[c[0],c])).values()].sort((a,b)=>a[0]-b[0]));}).catch(e=>{if(!ctrl.signal.aborted)setChartError(e.message);}).finally(()=>{if(!ctrl.signal.aborted)setChartBusy(false);});return()=>ctrl.abort();
 },[chartUrl,chartRetry]);
 const currentFeatures=useMemo(()=>mode==='history'?study.features as Features|null:features(candles,now/1000),[mode,study,candles,now]);
 const analogs=useMemo(()=>{
  if(!currentFeatures)return [];const token=mode==='history'?study.token:activePool?.token;const network=mode==='history'?study.chain:activePool?.chain;const seen=new Set<string>();
  return studies.filter(s=>s.features&&s.token!==token&&s.chain===network&&(mode!=='history'||s.signal<study.signal)).map(s=>{const f=s.features!,a=currentFeatures;return {...s,distance:Math.abs(f.change-a.change)/30+Math.abs(Math.log1p(f.range)-Math.log1p(a.range))+Math.abs(f.direction-a.direction)*2+Math.abs(Math.log1p(f.acceleration)-Math.log1p(a.acceleration))};}).sort((a,b)=>a.distance-b.distance).filter(s=>{if(seen.has(s.token))return false;seen.add(s.token);return true;}).slice(0,3);
 },[currentFeatures,mode,study,activePool]);
 const toggleFavorite=(p:Pool)=>setFavorites(list=>list.some(f=>f.id===p.id)?list.filter(f=>f.id!==p.id):list.length<30?[...list,p]:list);
 const displayCandles=candles.filter(c=>mode==='history'?c[0]>=study.signal-3600&&c[0]<=study.signal+14400:c[0]>=now/1000-14400);
 const scenario=activePool?.v1!=null&&fee!==''&&share!==''&&cost!==''&&Number(fee)>=0&&Number(fee)<=100&&Number(share)>=0&&Number(share)<=100&&Number(cost)>=0?activePool.v1*Number(horizon)*Number(fee)/100*Number(share)/100-Number(cost):null;
 return <main className="workspace">
 <header className="topbar"><div className="brand"><Radar size={28}/><b>PULL</b><span>LIQUIDITY RADAR</span></div><div className="status" suppressHydrationWarning><i/>{mode==='history'?'Архив · 2026':busy?'Обновление…':'Рынок · '+new Date(now).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</div></header>
 <div className="page-heading"><div><p className="eyebrow">АКТИВНЫЙ ПУЛЛИНГ</p><h1>Оборот. Диапазон. Риск.</h1><p className="muted">Условия для позиции, а не обещание доходности.</p></div><div className="profile"><label className="capital"><Wallet size={17}/>Позиция, $<Input type="number" min="1" max="1000000" value={capital} onChange={e=>setCapital(e.target.value)} aria-label="Капитал позиции"/></label><Select value={horizon} onValueChange={v=>v&&setHorizon(v)}><SelectTrigger aria-label="Горизонт удержания"><SelectValue>{horizon==='0.25'?'15 минут':horizon==='1'?'1 час':'4 часа'}</SelectValue></SelectTrigger><SelectContent>{[['0.25','15 минут'],['1','1 час'],['4','4 часа']].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div></div>
 <div className="navline"><Tabs value={mode} onValueChange={v=>{setMode(v as Mode);setQuery('');setLookup('');}}><TabsList variant="line"><TabsTrigger value="live"><Radar size={16}/>Радар</TabsTrigger><TabsTrigger value="favorites"><Star size={16}/>Избранное {favorites.length||''}</TabsTrigger><TabsTrigger value="history"><Activity size={16}/>Паттерны</TabsTrigger></TabsList></Tabs><div className="refresh-controls"><Button variant="outline" disabled={connecting} onClick={()=>{if(localSource){setLocalSource(false);localStorage.removeItem('pull-local-source');}else void connectLocal();}}>{connecting?'Подключаем…':localSource?'Компьютер ✓ · отключить':'Подключить компьютер'}</Button>{mode!=='history'&&<><label><Switch checked={auto} onCheckedChange={setAuto} aria-label="Автообновление"/>Авто · {AUTO_REFRESH_MS/1000} сек</label><small aria-live="polite">{busy?'Проверяем…':lastChecked?'Проверено '+new Date(lastChecked).toLocaleTimeString('ru-RU'):'Ожидаем данные'}</small><Button variant="outline" onClick={()=>setRefresh(v=>v+1)} disabled={busy}><RefreshCw size={15} className={busy?'spin':''}/>Обновить</Button></>}</div></div>
 <div className="panel toolbar"><div className="filters"><span className="usdg-filter">Пара: {pairLabel(chain)}</span><Select value={chain} onValueChange={v=>{if(v){setChain(v);setLookup('');}}}><SelectTrigger aria-label="Сеть"><SelectValue>{labels[chain]}</SelectValue></SelectTrigger><SelectContent>{['all',...chains].map(c=><SelectItem key={c} value={c}>{labels[c]}</SelectItem>)}</SelectContent></Select>{mode==='live'&&<Select value={feed} onValueChange={v=>v&&setFeed(v)}><SelectTrigger aria-label="Источник кандидатов"><SelectValue>{feed==='new'?'Новые пулы · до 24ч':'Трендовые токены GMGN'}</SelectValue></SelectTrigger><SelectContent><SelectItem value="trending">Трендовые пулы</SelectItem><SelectItem value="new">Новые пулы кандидатов · до 24ч</SelectItem></SelectContent></Select>}{mode!=='history'&&<label className="tvl-filter">TVL от $<Input type="number" min="0" value={minTvl} onChange={e=>setMinTvl(e.target.value)} aria-label="Минимальная ликвидность"/></label>}{mode!=='history'&&<><Select value={sortBy} onValueChange={v=>{if(v)setSortBy(v as SortKey);}}><SelectTrigger aria-label="Сортировать пулы"><SelectValue>{sortLabels[sortBy]}</SelectValue></SelectTrigger><SelectContent>{(Object.keys(sortLabels) as SortKey[]).map(k=><SelectItem key={k} value={k}>{sortLabels[k]}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={()=>setSortDirection(v=>v==='desc'?'asc':'desc')} aria-label={'Порядок сортировки: '+(sortDirection==='desc'?'по убыванию':'по возрастанию')}>{sortDirection==='desc'?'↓ По убыванию':'↑ По возрастанию'}</Button></>}</div><form className="search-box"  onSubmit={e=>{e.preventDefault();if(validAddress(query.trim())){if(chain==='all'){setError('Для поиска по адресу выберите одну сеть.');return;}setMode('live');setLookup(query.trim());}else setLookup('');}}><Search size={16}/><Input value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value)setLookup('');}} placeholder="Тикер или адрес токена" aria-label="Поиск токена"/><Button type="submit" variant="ghost" size="icon" aria-label="Найти"><ChevronRight size={16}/></Button></form></div>
 {error&&mode!=='history'&&<div className="error-box" role="alert"><AlertTriangle size={18}/>{error}</div>}
 <div className="section-meta"><span>{mode==='history'?historical.length+' исторических наблюдений · не PnL LP':ranked.length+' пулов · '+coverage}</span><span>{mode==='history'?'Признаки до сигнала':'Оценка по правилам, не обученная модель'}</span></div>
 <div className="workgrid"><section className="panel pool-list">
 {mode==='history'?<Table><TableHeader><TableRow><TableHead>Токен / сигнал</TableHead><TableHead>Цена 4ч</TableHead><TableHead>Минимум 4ч</TableHead><TableHead>Оборот 2–4ч</TableHead></TableRow></TableHeader><TableBody>{historical.map(s=><TableRow key={s.id} className={study.id===s.id?'selected':''}><TableCell><Button variant="ghost" onClick={()=>setStudyId(s.id)} className="token-button"><span className="token-avatar">{s.symbol.slice(0,2)}</span><span><b>{s.symbol}</b><small>{labels[s.chain]} · {s.date.slice(0,16)}</small></span></Button></TableCell><TableCell className={s.return4>=0?'positive':'negative'}>{pct(s.return4)}</TableCell><TableCell className="negative">{pct(s.low)}</TableCell><TableCell>{s.persistence.toFixed(2)}×</TableCell></TableRow>)}</TableBody></Table>:
 <Table><TableHeader><TableRow><TableHead>Пул</TableHead><TableHead>Оценка</TableHead><TableHead>Комиссия пула</TableHead><TableHead>Капитализация</TableHead><TableHead>Ликвидность</TableHead><TableHead>Объём пула 5м</TableHead><TableHead>Объём пула 1ч</TableHead><TableHead>Объём токена 1ч</TableHead><TableHead>Цена 1ч</TableHead><TableHead/></TableRow></TableHeader><TableBody>{ranked.map(({pool:p,rating:r})=><TableRow key={p.id} className={activePool?.id===p.id?'selected':''}><TableCell><Button variant="ghost" onClick={()=>setSelectedId(p.id)} className="token-button"><span className={'token-avatar '+p.chain}>{p.symbol.slice(0,2)}</span><span><b>{p.symbol}<span className="pair-quote"> / {p.quote}</span></b><small>{labels[p.chain]} · {p.dex}</small><small>{short(p.address)}</small><small>Данные {new Date(p.fetchedAt).toLocaleTimeString('ru-RU')}</small></span></Button></TableCell><TableCell><span className={'score '+(r.score===null?'unknown':r.score>=65?'good':r.score>=40?'mid':'bad')}>{r.score??'—'}</span><small className="regime">{r.stale?'Данные устарели':r.regime}</small></TableCell><TableCell><span title={[p.feeSource,p.feeNote,p.feeCheckedAt?'Проверено '+new Date(p.feeCheckedAt).toLocaleTimeString('ru-RU'):''].filter(Boolean).join(' ')}>{p.feePercent==null?'н/д':p.feePercent+'%'}</span>{p.feeKind==='dynamic'&&<small className="regime">Динамическая</small>}{p.feePercent===0&&<small className="regime">Hook-сборы отдельно</small>}</TableCell><TableCell>{money(p.marketCap??null)}</TableCell><TableCell>{money(p.liquidity)}</TableCell><TableCell>{money(p.v5)}<small className={p.volumeSignal?.kind==='surge'?'positive regime':p.volumeSignal?.kind==='fading'?'negative regime':'muted regime'}>{volumeLabel(p.volumeSignal)}</small></TableCell><TableCell>{money(p.v1)}<small className="regime">{r.accel===null?'нет базы':r.accel.toFixed(1)+'× темп 5м'}</small></TableCell><TableCell title="Общий объём токена по GMGN; не участвует в расчёте комиссии пула">{money(p.tokenV1??null)}<small className="regime">GMGN · 5м {money(p.tokenV5??null)}{p.tokenFetchedAt&&now-p.tokenFetchedAt>600000?' · устарело':''}</small></TableCell><TableCell className={(p.change1||0)>=0?'positive':'negative'}>{pct(p.change1)}</TableCell><TableCell><Button variant="ghost" size="icon" aria-label={(favorites.some(f=>f.id===p.id)?'Убрать ':'Сохранить ')+p.symbol} aria-pressed={favorites.some(f=>f.id===p.id)} onClick={()=>toggleFavorite(p)}><Star size={17} fill={favorites.some(f=>f.id===p.id)?'#e7b36e':'none'}/></Button></TableCell></TableRow>)}</TableBody></Table>}
 {(mode==='history'?!historical.length:!ranked.length)&&<div className="empty-state"><Radar size={36}/><h2>{busy&&mode!=='history'?'Ищем пулы…':'Нет результатов'}</h2><p>В выбранной выборке нет подходящих пулов с {pairLabel(chain)}. Измените сеть или найдите токен по адресу.</p>{lookup&&<Button variant="outline" onClick={()=>{setLookup('');setQuery('');}}>Вернуться к радару</Button>}</div>}</section>
 <aside className="panel detail">{(mode==='history'?historical.length>0:activePool)?<>
 <div className="detail-top"><p className="eyebrow">{mode==='history'?'ИСТОРИЧЕСКИЙ СЛУЧАЙ':'УСЛОВИЯ ПУЛА'}</p>{activePool&&<a href={activePool.url} target="_blank" rel="noreferrer" aria-label="Открыть пул в источнике"><ArrowUpRight size={20}/></a>}</div>
 {lpLink?.url?<a className="krystal-link" href={lpLink.url} target="_blank" rel="noopener noreferrer">Открыть пул в {lpLink.label} <ArrowUpRight size={16}/></a>:<p className="muted">Прямая ссылка {lpLink?.label||'на пул'} для этого протокола пока не определена.</p>}
 <h2>{mode==='history'?study.symbol:activePool?.symbol}<small>{mode==='history'?study.date:labels[activePool!.chain]+' · '+activePool!.quote}</small></h2>
 {mode!=='history'&&<div className="detail-score"><span className={'score '+(selected!.rating.score!==null&&selected!.rating.score>=65?'good':'mid')}>{selected!.rating.score??'—'}</span><div><b>{selected!.rating.regime}</b><p className="muted">Предварительная оценка условий</p></div></div>}
 <div className="chart-box" aria-live="polite">{chartBusy?<p className="muted">Загружаем свечи…</p>:mode!=='history'&&activePool&&(chartError||displayCandles.length<2)?<><p className="muted">{chartError?chartError+' Показан встроенный график.':'График пула GeckoTerminal'}</p><iframe key={activePool.id} title={'График пула '+activePool.symbol+' в GeckoTerminal'} src={'https://www.geckoterminal.com/'+activePool.chain+'/pools/'+activePool.address+'?embed=1&info=0&swaps=0&light_chart=0&chart_type=price&resolution=5&bg_color=101820'} className="external-chart" allow="fullscreen"/><div className="chart-actions"><Button variant="outline" onClick={requestCandles}>{requestedChart===chartIdentity?'Повторить загрузку свечей':'Загрузить свечи для аналогов'}</Button><a href={'https://www.geckoterminal.com/'+activePool.chain+'/pools/'+activePool.address} target="_blank" rel="noopener noreferrer">Открыть график ↗</a></div><small className="muted">Встроенный график показывает пару на стороне источника. Аналоги доступны только после загрузки проверенных свечей токена.</small></>:chartError?<><p className="negative">{chartError}</p><Button onClick={()=>setChartRetry(v=>v+1)}>Повторить</Button></>:<PriceChart candles={displayCandles} signal={mode==='history'?study.signal:undefined}/>}</div>
 {mode==='history'?<div className="detail-metrics"><div><span>Цена через 4ч</span><b className={study.return4>=0?'positive':'negative'}>{pct(study.return4)}</b></div><div><span>Устойчивость оборота</span><b>{study.persistence.toFixed(2)}×</b></div></div>:<>
 <div className="detail-metrics"><div><span>Комиссия пула</span><b>{activePool!.feePercent==null?'н/д':activePool!.feePercent+'%'}</b></div></div><p className="muted">{activePool!.feePercent==null?(activePool!.feeNote||'Источник не сообщил тариф этого пула.'):activePool!.feeSource+'. '+(activePool!.feeNote||'')}</p><p className="muted">{volumeLabel(activePool!.volumeSignal)}{activePool!.volumeSignal?.ratio!=null?' · '+activePool!.volumeSignal.ratio.toFixed(1)+'× предыдущего темпа':''}</p><div className="detail-metrics"><div><span>Капитализация</span><b>{money(activePool!.marketCap??null)}</b></div><div><span>FDV (не капитализация)</span><b>{money(activePool!.fdv??null)}</b></div></div><div className="detail-metrics"><div><span>Объём 5 минут</span><b>{money(activePool!.v5)}</b></div><div><span>Объём 1 час</span><b>{money(activePool!.v1)}</b></div></div><div className="detail-metrics"><div><span>Оборот / TVL за 1ч</span><b>{selected!.rating.turnover?.toFixed(2)??'н/д'}×</b></div><div><span>Позиция / TVL</span><b>{activePool!.liquidity?(selected!.rating.capitalRatio*100).toFixed(2)+'%':'н/д'}</b></div></div>
 <h3>Из чего складывается оценка</h3><div className="components">{Object.entries(selected!.rating.components).map(([key,value])=><div key={key}><span>{({turnover:'Оборот · 30%',persistence:'Темп объёма · 25%',range:'Движение USD · 30%',depth:'Размер позиции · 15%'} as Record<string,string>)[key]}</span><div className="track"><i style={{width:(value??0)+'%'}}/></div><b>{value===null?'—':Math.round(value)}</b></div>)}</div>
 <ul className="reasons">{[...selected!.rating.missing,...selected!.rating.reasons].map(r=><li key={r}>{r}</li>)}</ul>
 <p className="muted">Низкий сдвиг USD не подтверждает узкий диапазон цены пары. Безопасность токена не проверена.</p>
 <details className="scenario"><summary>Сценарий комиссий для {'$'}{amount}</summary><p className="muted">При сохранении часового оборота. Введите известную комиссию LP и долю позиции в активной ликвидности.</p><div className="scenario-inputs"><label>Комиссия LP, %<Input type="number" min="0" max="100" step=".01" value={fee} onChange={e=>setFee(e.target.value)} placeholder="Неизвестна"/></label><label>Активная доля, %<Input type="number" min="0" max="100" step=".01" value={share} onChange={e=>setShare(e.target.value)} placeholder="Неизвестна"/></label><label>Все расходы, $<Input type="number" min="0" step=".1" value={cost} onChange={e=>setCost(e.target.value)}/></label></div><p><b>{scenario===null?'Нужны параметры позиции':money(scenario)}</b> {scenario===null?'':'комиссий за вычетом расходов'}</p><p className="muted">Без изменения стоимости активов. Это сценарий, не чистый PnL и не прогноз.</p></details>
 <small className="source-meta">{activePool!.source} · {activePool!.fetchedAt?new Date(activePool!.fetchedAt).toLocaleString('ru-RU'):'не обновлено'} · {short(activePool!.address)}</small></>}
 <hr/><h3>Похожие исторические окна</h3><p className="muted">Та же сеть, другие токены. Сравнение цены, амплитуды, направленности и темпа объёма до решения.</p>
 {!currentFeatures?<p className="muted">Нужно не менее часа достаточно частых свечей.</p>:!analogs.length?<p className="muted">В библиотеке нет подходящих предшествующих случаев.</p>:analogs.map(a=><button type="button" className="analog" key={a.id} onClick={()=>{setMode('history');setChain(a.chain);setStudyId(a.id);setQuery('');}}><span><b>{a.symbol}</b><small>{a.date.slice(0,16)}</small></span><span className={a.return4>=0?'positive':'negative'}>{pct(a.return4)}<small>цена 4ч</small></span><ChevronRight size={15}/></button>)}
 <div className="notice">На позиции {'$'}{amount} каждый $1 расходов — {(100/amount).toFixed(2)}% капитала. Сходство не даёт вероятности прибыли.</div>
 </>:<div className="empty-detail"><Activity size={30}/><h3>Выберите пул</h3><p className="muted">Здесь появятся график, причины оценки и аналоги.</p></div>}</aside></div>
 <footer><span>GMGN · кандидаты и объём токена / DEX Screener · показатели пулов</span><span>Проверка каждые {AUTO_REFRESH_MS/1000} сек при видимой странице. Пулы обновляются порциями; время данных указано в каждой строке.</span></footer>
 </main>;
}
